<a href="https://colab.research.google.com/github/ipuerta/apuntes/blob/main/notebooks/Apuntes_Tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensores (vectores, matrices) con NumPy, PyTorch y TensorFlow**

In [2]:
import numpy as np
import torch
import tensorflow as tf
import matplotlib.pyplot as plt

**Crear un vector**

Con NumPy

In [6]:
np_x = np.array([25, 2, 5])
np_x

array([25,  2,  5])

In [7]:
np_x_float = np.array([25, 2, 5], dtype=np.float16)
np_x_float

array([25.,  2.,  5.], dtype=float16)

In [8]:
len(np_x)

3

In [10]:
type(np_x)

numpy.ndarray

In [11]:
np_x.shape

(3,)

In [15]:
np_x_float[0]

25.0

In [14]:
type(np_x_float[0])

numpy.float16

**Ejercicios**

Demostrar que una matriz identidad es ortogonal:
1.   Calcular el "dot product" multiplicando cada fila con el resto, el resultado debe ser 0 --> las filas son ortogonales
2.   Calcular el "L2 norm" de cada columna, el resultado debe ser 1 --> las columnas son ortonormales

Nota: Todas las filas y columnas tienen que ser (y son) ortogonales y ortonormales, pero sólo calcularemos estos dos puntos.


In [16]:
# Creo matriz identidad
m_identidad = np.array([[1, 0, 0],[0, 1, 0],[0, 0, 1]])
m_identidad

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [19]:
# Comprobamos que todas las columnas son ortogonales entre sí calculando el "dot product" entre ellas (debe ser 0)
np.dot(m_identidad[:,0], m_identidad[:,1])

0

In [20]:
np.dot(m_identidad[:,1], m_identidad[:,2])

0

In [21]:
np.dot(m_identidad[:,2], m_identidad[:,0])

0

In [32]:
# Calculamos el L2 de cada columna
np.linalg.norm(m_identidad[0,:])

1.0

In [33]:
np.linalg.norm(m_identidad[1,:])

1.0

In [34]:
np.linalg.norm(m_identidad[2,:])

1.0

Repetir el ejercicio con la siguiente matriz:

[2/3, 1/3, 2/3]

[-2/3, 2/3, 1/3]

[1/3, 2/3 ,2/3]

In [38]:
# Creo matriz
m_ejercicio = np.array([[2/3, 1/3, 2/3],[-2/3, 2/3, 1/3],[1/3, 2/3, -2/3]])
m_ejercicio

array([[ 0.66666667,  0.33333333,  0.66666667],
       [-0.66666667,  0.66666667,  0.33333333],
       [ 0.33333333,  0.66666667, -0.66666667]])

In [39]:
# Comprobamos que todas las columnas son ortogonales entre sí calculando el "dot product" entre ellas (debe ser 0)
np.dot(m_ejercicio[:,0], m_ejercicio[:,1])

0.0

In [40]:
np.dot(m_ejercicio[:,1], m_ejercicio[:,2])

0.0

In [41]:
np.dot(m_ejercicio[:,2], m_ejercicio[:,0])

0.0

In [42]:
# Calculamos el L2 de las filas
np.linalg.norm(m_ejercicio[0,:])

1.0

In [43]:
np.linalg.norm(m_ejercicio[1,:])

1.0

In [44]:
np.linalg.norm(m_ejercicio[2,:])

1.0